kind: pipeline
type: docker
name: default

steps:
- name: build-image
  image: plugins/docker
  settings:
    custom_dns: 192.168.1.7
    dockerfile: Dockerfile
    build_args:
      - APT_PROXY=teledhil.eu
